export const ICONS = {
  dislike: "dislike",
  like: "like",
  search_image: "search_image",
  share: "share",
  link: "link",
  download: "download",
  drop: "drop",
  close: "close",
  back: "back",
  avatar: "avatar",
  filter: "filter",
  logout: "logout",
  camera_simple: "camera_simple",
  filter_settings: "filter_settings",
  plus: "plus",
  crop: "crop",
  collapse: "collapse",
  trash: "trash",
  info: "info",
  box3d: "box3d",
  settings: "settings",
  gallery: "gallery",
  next_arrow: "next_arrow",
  minus: "minus",
  plus_rounded: "plus_rounded",
  search: "search",
  email: "email",
  call: "call",
  error: "error",
  camera: "camera",
} as const;

export type SUPPORTED_ICON = keyof typeof ICONS;
