export const ICONS = {
  arrow_down: 'arrow_down',
  auto_focus: 'auto_focus',
  avatar: 'avatar',
  back: 'back',
  box3d: 'box3d',
  call: 'call',
  camera_simple: 'camera_simple',
  camera: 'camera',
  caret_left: 'caret_left',
  caret_right: 'caret_right',
  close: 'close',
  collapse: 'collapse',
  crop: 'crop',
  dislike: 'dislike',
  download: 'download',
  drop: 'drop',
  email: 'email',
  error: 'error',
  experience_visual_search: 'experience_visual_search',
  filter_settings: 'filter_settings',
  filter: 'filter',
  gallery: 'gallery',
  info: 'info',
  like: 'like',
  link: 'link',
  logout: 'logout',
  machine_view: 'machine_view',
  minus: 'minus',
  next_arrow: 'next_arrow',
  plus_rounded: 'plus_rounded',
  plus: 'plus',
  powered_by_nyris: 'powered_by_nyris',
  search_image: 'search_image',
  search: 'search',
  settings: 'settings',
  share: 'share',
  spare: 'spare',
  trash: 'trash',
  wear: 'wear',
} as const;

export type SUPPORTED_ICON = keyof typeof ICONS;
