import { SearchState } from './types';

export const initialState: SearchState = {
  categoryPredictions: [],
  codes: [],
  fetchingResults: false,
  filterOptions: [],
  filters: [],
  imageThumbSearchInput: '',
  isShowModalDetailItemMobile: false,
  preFilter: {},
  loadingSearchAlgolia: false,
  preFilterDropdown: false,
  imageCaptureHelpModal: false,
  regions: [],
  requestImage: undefined,
  results: [],
  selectedRegion: undefined,
  textSearchInputMobile: '',
  valueTextSearch: {
    configure: { filters: '' },
    page: 1,
    refinementList: '',
  },
  postFilter: {},
  showFeedback: false,
  firstSearchImage: '',
  firstSearchResults: null,
  firstSearchPrefilters: null,
  firstSearchThumbSearchInput: null,
  countOfSearch: 0,
};
